import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useDispatch, useSelector } from 'react-redux';
import { todoActions } from '@root/to-do/slice';
import { RootState } from './store';
import { ToDoItem } from '@root/to-do/types';
import { useEffect } from 'react';
import ToDoForm from '@root/to-do/components/ToDoForm';

export default function Home() {
  const dispatch = useDispatch();
  const toDos = useSelector((state: RootState) => state.toDoReducer.toDos);

  useEffect(() => {
    dispatch(todoActions.requestGetToDo());
  }, [dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Saga To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>To-Do List</h1>
        <ToDoForm />
        {toDos.map((toDo: ToDoItem) => (
          <div className={styles.card} key={toDo.id}>
            <div>
              <span>{toDo.title}</span>
              <span>{toDo.description}</span>
              <span>{toDo.status}</span>
            </div>
            <div>
              <button>Open</button>
              <button>In Progress</button>
              <button>Done</button> <button>X</button>
            </div>
          </div>
        ))}
      </main>
    </div>
  );
}
